- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-gui-helm-lint
        - nebulous-gui-build-container-images
        - nebulous-gui-hadolint
        - nebulous-platform-apply-helm-charts:
            dependencies:
              - name: nebulous-gui-build-container-images
                soft: true
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-gui-helm-lint
        - nebulous-gui-upload-container-images
        - nebulous-gui-hadolint
        - nebulous-platform-apply-helm-charts:
            dependencies:
              - name: nebulous-gui-upload-container-images
                soft: true
        - nox-linters
    promote:
      jobs:
        - nebulous-gui-promote-container-images
