name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-gui-builder:
    name: Build and push gui-builder
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: gui
      image-name: gui-builder
      build-args: |
        BUILD_ID="${{github.sha}}"
        BUILD_CONTEXT="${{github.ref_name}}"
    secrets: inherit
